### ISSUE TITLE
Compatibility with Swift 2

### ISSUE THREAD

**Issue by keduardo2117** [maximbilan/ios_calendar#12]
Today, Aug 22 of 2016, I installed through CocoaPods this module and got this series of errors, looks like some protocols and functions are deprecated/changed in Swift 2.0
<img width="545" alt="screen shot 2016-08-22 at 10 27 39 am" src="https://cloud.githubusercontent.com/assets/1683339/17860508/28c25030-6853-11e6-8298-dc4e665baa23.png">

**Comment by maximbilan** [comment]
Hi,

What version of CocoaPods do you use?
I've just installed in Swift project with helping 1.0.1 version without any issues.

Thanks.
