### ISSUE TITLE
shouldShowHeaders 

### ISSUE THREAD

**Issue by willeminna** [maximbilan/ios_calendar#14]
Hello, first I want to say that this is a great app! 
I have only one problem though, when setting the bool for shouldShowHeaders to yes , it put's the headers but shows the days over them. After a swipe it put's them where they should be. Changing the bool to YES from your code solves this problem . Any idea how I could solve this ?

**Comment by maximbilan** [comment]
Hi,

You should the next lines in this case:

`self.calendarView.shouldShowHeaders = YES;`
`[self.calendarView refresh];`

Best regards,
Maxim
