### ISSUE TITLE
setCurrentDate

### ISSUE THREAD

**Issue by pvclever** [maximbilan/ios_calendar#15]
Hello, Maxim !
I set utc date (it comes from server) and see wrong date in the calendar
Why don't you set TimeZone in this method?
- (void)setCurrentDate:(NSDate *)date

Thank you

**Comment by maximbilan** [comment]
Hi,

Thanks for your question. You can apply timezone for your date and then send to the calendar control. I think it's not necessary to have a separated method, anyway, you can create a fork and implement timezone method.
