### ISSUE TITLE
Extra UI Options

### ISSUE THREAD

**Issue by estansbury** [maximbilan/ios_calendar#5]
Hey, 
This is a pretty snazzy component, and I was hoping to use it in one of the projects I'm working on. 

However, there are a couple of UI cases that this doesn't really cover, such as a marker for today instead of/in addition to the currently selected date, or removing the month and year headers. 

So I'm planning to make some minimally invasive, backwards compatible edits, and I'd love to give them back to the project if you're interested.

**Comment by maximbilan** [comment]
Ok, I don't mind.
