### ISSUE TITLE
fontName not properly set

### ISSUE THREAD

**Issue by vrsantos** [maximbilan/ios_calendar#9]
Hi!

I'm using your calendar and I was attempting to change the fontName and it wasn't updating to the font that I wanted. After taking a look at your implementation file, I notice that you use kCalenderViewDefaultFont instead of the fontName property. Do you mind if I make a pull request and fix this change?

By the way, I also plan on doing some more UI updates in the future if you're okay with that! Things like highlighting the week, etc.

Thanks!
Vivian Santos

**Comment by maximbilan** [comment]
Hi,

Ok, I will confirm your fixes or improvements. Feel free. Thank you.
